# Python Chilla 10 hours video
## Basics of Python
### This file contains the basic concept of python by Ammar Bhai

### 1- Numpy 
> - Same data type t 
> - Store large data than list 
> - consumes less memory 
> - works for big numerical operations 


In [2]:
import numpy as np 
a = np.arange(6)
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [4]:
b = np.array([5,5,5,5])
b

array([5, 5, 5, 5])

In [5]:
type(b)

numpy.ndarray

In [6]:
c = np.array([[5,5,5],[4,4,4],[3,3,3]])
c 

array([[5, 5, 5],
       [4, 4, 4],
       [3, 3, 3]])

In [7]:
d = np.zeros(2)
d

array([0., 0.])

In [8]:
e = np.ones(4)
e

array([1., 1., 1., 1.])

In [9]:
f = np.empty(3)
f 

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313])

In [10]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
b = np.linspace(0,15,num=7)
b

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ])

### 2D Array 


In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# 3D Arrays 

c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])